import { pageScript } from "./page-script.js";
import { pageStyles } from "./page-styles.js";

const recoveryStyles = `:root{color-scheme:dark;font-family:Geist,system-ui,sans-serif;background:#111113;color:#8b8b93}body{margin:0;min-height:100vh;display:grid;place-items:center}p{max-width:36rem;padding:24px;line-height:1.5}`;

export const bootstrapHtml = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Review Tutor · Pickforge</title><style>${recoveryStyles}</style></head>
<body><p id="message" hidden>Review Tutor session not found in this tab. Reopen /review-tutor in Pi, or paste the full tutor link.</p><script>
let token = null;
try { token = sessionStorage.getItem("reviewTutorSession"); } catch {}
if (token) location.replace("/?session=" + encodeURIComponent(token));
else document.getElementById("message").hidden = false;
</script></body></html>`;

export const staleSessionHtml = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Review Tutor · Pickforge</title><style>${recoveryStyles}</style></head>
<body><p>This Review Tutor session has ended. Reopen /review-tutor in Pi.</p><script>
try { sessionStorage.removeItem("reviewTutorSession"); } catch {}
</script></body></html>`;

export const pageHtml = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer">
<title>Review Tutor · Pickforge</title>
<style>${pageStyles}</style></head>
<body>
<header class="topbar" role="banner"><svg class="mark" aria-hidden="true" viewBox="0 0 24 24" width="18" height="18"><path d="M3 9V3h6M21 15v6h-6M3 15v6h6" fill="none" stroke="#F2F2F3" stroke-width="2" stroke-linecap="square"/><circle cx="17" cy="7" r="2.6" fill="#FF7A1A"/></svg><strong class="brand">Review Tutor<span class="sep"> · </span>Pickforge</strong><div class="source-summary"><span id="top-source">No source</span></div><button id="open-config" class="ghost open-config" aria-haspopup="dialog" aria-controls="config-dialog">Config</button><span id="connection" role="status" aria-live="polite" class="connection" data-state="starting">starting</span></header>
<div id="error" role="alert" tabindex="-1" class="error"></div><div id="lifecycle" role="status" aria-live="polite" class="sr-only"></div>
<main class="workbench">
<section id="diff-pane" class="diff-pane" role="region" aria-label="Code changes">
<div id="source-setup" class="source-setup"><span class="eyebrow">Source</span><h1>Pick a source.</h1><p>Local input. Immutable snapshot. Nothing leaves this machine.</p><div class="source-grid">
<label class="field"><span>Source</span><select id="kind"><option value="worktree">Worktree</option><option value="staged">Staged</option><option value="commit">Commit</option><option value="range">Range</option><option value="pr">GitHub PR</option><option value="paste">Pasted code</option></select></label>
<label id="revision-field" class="field source-field" hidden><span>Commit</span><input id="revision" maxlength="256" placeholder="HEAD~1"></label>
<div id="range-field" class="two source-field" hidden><label class="field"><span>From</span><input id="range-from" maxlength="256" placeholder="main"></label><label class="field"><span>To</span><input id="range-to" maxlength="256" placeholder="feature"></label></div>
<label id="pr-field" class="field source-field" hidden><span>Pull request URL</span><input id="pr-url" type="url" placeholder="https://github.com/owner/repo/pull/123"></label>
<div id="paste-field" class="source-field" hidden><label class="field"><span>Pasted code</span><textarea id="paste" maxlength="1048576"></textarea></label><label class="field"><span>Label (optional)</span><input id="paste-label" maxlength="256"></label></div>
<div class="source-actions"><button id="load" class="primary">Load source</button></div></div></div>
<div class="toolbar"><div id="view-switch" class="view-switch" role="tablist" aria-label="Workspace view"><button id="view-diff" class="view-tab" role="tab" aria-selected="true" aria-controls="diff" tabindex="0">Diff</button><button id="view-structure" class="view-tab" role="tab" aria-selected="false" aria-controls="structure-section" tabindex="-1">Structure</button><button id="view-log" class="view-tab" role="tab" aria-selected="false" aria-controls="log-section" tabindex="-1">Learning log</button></div><label class="sr-only" for="files">Files</label><select id="files" disabled><option>Files (0)</option></select><button id="previous-file" class="ghost" aria-label="Previous file" disabled>‹</button><button id="next-file" class="ghost" aria-label="Next file" disabled>›</button><button id="select-lines" class="ghost select-toggle" aria-pressed="false">Select lines</button><button id="open-composer" class="ghost ask-open" aria-label="Ask the tutor">Ask</button><span id="totals" class="totals"><span class="add">+0</span> <span class="delete">−0</span></span><button id="change-source" class="ghost source-change" aria-label="Change source" hidden>Change</button></div>
<section id="tutor" class="tutor" role="region" aria-labelledby="tutor-title" tabindex="-1"><div class="dialog-head"><div><span class="eyebrow">Tutor</span><h2 id="tutor-title">Ask the tutor</h2></div><button id="close-tutor" class="ghost close-dialog">Close</button></div><p class="lede">Select code. Ask anything.</p>
<div id="selection-card" class="selection-card"><div class="selection-head"><strong id="selection-summary" class="selection-meta">No code selected</strong><button id="clear-selection" class="ghost" hidden>Clear</button></div><div id="selection-preview" class="selection-preview"></div><p id="selection-helper" class="helper" hidden>Shift-click line numbers to extend the selection. Select + to ask.</p></div>
<label class="field"><span>Mode</span><select id="mode"><option value="explain">Explain</option><option value="quiz">Quiz me</option></select></label><label class="field"><span>Question</span><textarea id="question" class="question" maxlength="4096" placeholder="What does this change do?"></textarea></label>
<div class="ask-row"><button id="ask" class="primary" aria-busy="false" disabled>Ask</button><button id="cancel" class="ghost" disabled>Cancel</button><span id="question-state" hidden></span></div><p id="ask-helper" class="ask-helper">Load a source and enter a question.</p><div id="answer" class="answer" hidden><div class="answer-head"><span class="answer-label" aria-hidden="true">Answer</span><div id="history-pager" class="history-pager" hidden><button id="history-previous" class="ghost" aria-label="Newer saved answer">‹</button><span id="history-position"></span><button id="history-next" class="ghost" aria-label="Older saved answer">›</button></div></div><div id="answer-text" class="answer-text"></div><div id="answer-tail" class="helper"></div></div></section>
<div id="diff-scroll" class="diff-scroll"><div id="diff" role="tabpanel" aria-labelledby="view-diff"><p class="empty">Load a source to begin reviewing.</p></div><section id="structure-section" class="structure-section" role="tabpanel" aria-labelledby="view-structure structure-title" hidden><h2 id="structure-title" class="sr-only" tabindex="-1">Connections</h2><div id="structure-mode-switch" class="view-switch structure-mode-switch" role="tablist" aria-label="Structure mode" hidden><button id="structure-mode-list" class="view-tab" role="tab" aria-selected="true" aria-controls="structure-content" tabindex="0">List</button><button id="structure-mode-graph" class="view-tab" role="tab" aria-selected="false" aria-controls="structure-graph" tabindex="-1">Graph</button></div><div id="structure-shared"></div><div id="structure-content" role="tabpanel" aria-labelledby="structure-mode-list" tabindex="0"></div><div id="structure-graph" role="tabpanel" aria-labelledby="structure-mode-graph" tabindex="0" hidden></div></section><section id="log-section" class="log-section" role="tabpanel" aria-labelledby="view-log log-title" hidden><div class="log-head"><h2 id="log-title" class="eyebrow" tabindex="-1">Learning log</h2><label class="sr-only" for="log-filter">Filter</label><select id="log-filter"><option value="all">All</option><option value="later">Review later</option></select><button id="refresh" class="ghost">Refresh</button><button id="export" class="ghost">Export HTML</button></div><div id="log"></div></section></div>
</section>
<aside id="config-dialog" class="rail" aria-label="Configuration" tabindex="-1"><div class="rail-head"><span id="config-title" class="eyebrow rail-eyebrow">Configuration</span><button id="toggle-rail" class="ghost rail-toggle" aria-expanded="true" aria-controls="config-section" aria-label="Collapse configuration">›</button></div><section id="config-section" class="config-section"><label class="field"><span>Harness</span><select id="harness"><option value="pi">Pi</option></select></label><p class="helper">Pi is the only connected harness.</p><div class="two"><label class="field"><span>Model</span><select id="model"></select></label><label class="field"><span>Thinking</span><select id="thinking"></select></label></div><label class="field"><span>Explanation language</span><select id="language"></select></label><fieldset class="matches"><legend class="group-label">Closest matches</legend><p class="helper">Up to three languages you already know.</p><div class="three"><label class="field"><span>Match 1</span><select id="match-1" class="match"></select></label><label class="field"><span>Match 2</span><select id="match-2" class="match"></select></label><label class="field"><span>Match 3</span><select id="match-3" class="match"></select></label></div></fieldset><div class="config-actions"><button id="jump-log" class="ghost">Learning log</button></div></section></aside></main><button id="mobile-ask" class="mobile-ask">Ask the tutor</button>
<script>${pageScript}</script></body></html>`;
